#!/bin/bash

APROX_VERSION='@project.version@'
APROX_FLAVOR='savant'

APROX_PORTS="-p 8081:8081"
#APROX_PORTS="${APROX_PORTS} -p 8000:8000" #For debugging.

APROX_BINARY_URL="http://repo.maven.apache.org/maven2/org/commonjava/aprox/launch/aprox-launcher-${APROX_FLAVOR}/${APROX_VERSION}/aprox-launcher-${APROX_FLAVOR}-${APROX_VERSION}-launcher.tar.gz"

APROX_ENVARS="-e APROX_BINARY_URL=${APROX_BINARY_URL}"

#APROX_ETC_URL=http://github.com/myuser/my-aprox-etc.git
#APROX_ENVARS="${APROX_ENVARS} -e APROX_ETC_URL=${APROX_ETC_URL}"

#APROX_OPTS=''
#APROX_ENVARS="${APROX_ENVARS} -e APROX_OPTS=${APROX_OPTS}"

SSHDIR=$HOME/.ssh

chcon -Rt svirt_sandbox_file_t $SSHDIR

set -x
docker run \
    ${APROX_PORTS} \
    ${APROX_ENVARS} \
    -t --name="aprox" \
    -v $SSHDIR:/tmp/ssh-config \
    buildchimp/aprox
